### ISSUE TITLE
Feature: Add translations for jurisdiction customizations

### ISSUE THREAD

**Issue by stefanoschrs** [Path-Check/gaen-mobile#629]
We are looking for a clean way to add further translations for the customizations that we do (we suppose other jurisdictions will need that as well).

The initial idea (that we are currently using) is to add a `${code}-custom.json` file with the custom translations and then merge it on the base `${code}.json` file. The only problem is that you need to hardcode these imports, as dynamic ones are not working.

**Custom translations:** https://github.com/rise-center/cy.gov.dmrid.covtracer/blob/master/src/locales/en-custom.json  
**Importing:** https://github.com/rise-center/cy.gov.dmrid.covtracer/blob/master/src/locales/languages.ts#L39  
**Merging:** https://github.com/rise-center/cy.gov.dmrid.covtracer/blob/master/src/locales/languages.ts#L84

Any thoughts on how to improve this?

**Comment by johnschoeman** [comment]
Given how the i18n scripts work, it's hard to do anything with translations dynamically, (other than change the selected local.) So that leaves build time options as the mostly likely bet. Have you considered a build time script that merges the two json files? This sounds to me like it would minimize the divergence of the fork from the main repo.

That said, your solution here seems viable to me as well.

This is something on our roadmap that we would like to do eventually, but not sure when we will be able to get to it. So thanks for opening this issue and please let us know how you progress on this one.

**Comment by stefanoschrs** [comment]
A script to merge the custom files also sounds like a good idea yes!

**Comment by johnschoeman** [comment]
Awesome, I'm going to close this issue for now then. Please reopen it if anything else on this topic comes up.
